-- MySQL Script generated by MySQL Workbench
-- sáb 25 ene 2020 17:30:16 WET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Direccion` (
  `id` INT NOT NULL,
  `ciudad` VARCHAR(45) NULL,
  `calle` VARCHAR(45) NULL,
  `numero` INT NULL,
  `codigo_postal` CHAR(5) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `numero_copias_hechas` INT NOT NULL,
  `DNI` VARCHAR(10) NULL,
  `direccion_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `direccion_idx` (`direccion_id` ASC),
  CONSTRAINT `direccion`
    FOREIGN KEY (`direccion_id`)
    REFERENCES `mydb`.`Direccion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categoria` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Autor` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Recurso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Recurso` (
  `id` INT NOT NULL,
  `tipo` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Libro` (
  `recurso_id` INT NOT NULL,
  `ISBN` CHAR(13) NOT NULL,
  `titulo` VARCHAR(45) NULL,
  `numero_de_paginas` INT NULL,
  `area` VARCHAR(10) NULL,
  `estante` INT NULL,
  `categoria_id` INT NULL,
  `tipo_casa_o_sala` CHAR(1) NOT NULL,
  `autor_id` INT NULL,
  INDEX `fk_book_book_category1_idx` (`categoria_id` ASC),
  INDEX `autor_idx` (`autor_id` ASC),
  PRIMARY KEY (`ISBN`),
  CONSTRAINT `categoria`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `mydb`.`Categoria` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `autor`
    FOREIGN KEY (`autor_id`)
    REFERENCES `mydb`.`Autor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `recurso_padre`
    FOREIGN KEY (`recurso_id`)
    REFERENCES `mydb`.`Recurso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleado` (
  `seguridad_social` VARCHAR(20) NOT NULL,
  `turno` VARCHAR(45) NULL,
  `horario` VARCHAR(45) NULL,
  `salario` INT NULL,
  `direccion_id` INT NOT NULL,
  PRIMARY KEY (`seguridad_social`),
  INDEX `fk_Empleado_Direccion1_idx` (`direccion_id` ASC),
  CONSTRAINT `fk_Empleado_Direccion1`
    FOREIGN KEY (`direccion_id`)
    REFERENCES `mydb`.`Direccion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Revista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Revista` (
  `recurso_id` INT NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `fotocopias_realizadas` TINYINT(1) NOT NULL,
  PRIMARY KEY (`titulo`),
  CONSTRAINT `recurso_padre`
    FOREIGN KEY (`recurso_id`)
    REFERENCES `mydb`.`Recurso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Portatil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Portatil` (
  `recurso_id` INT NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`modelo`, `marca`),
  CONSTRAINT `recurso_padre`
    FOREIGN KEY (`recurso_id`)
    REFERENCES `mydb`.`Recurso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Prestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Prestamo` (
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `usuario_id` INT NOT NULL,
  `empleado_seguridad_social` VARCHAR(20) NOT NULL,
  `casa_o_sala` VARCHAR(4) NOT NULL,
  `Libro_ISBN` CHAR(13) NULL,
  `Revista_titulo` VARCHAR(45) NULL,
  `Portatil_modelo` VARCHAR(45) NULL,
  `Portatil_marca` VARCHAR(45) NULL,
  INDEX `fk_book_borrow_service_student1_idx` (`usuario_id` ASC),
  INDEX `fk_book_reservation_library_member1_idx` (`empleado_seguridad_social` ASC),
  PRIMARY KEY (`empleado_seguridad_social`, `usuario_id`, `fecha_inicio`),
  INDEX `fk_Prestamo_Libro1_idx` (`Libro_ISBN` ASC),
  INDEX `fk_Prestamo_Revista1_idx` (`Revista_titulo` ASC),
  INDEX `fk_Prestamo_Portatil1_idx` (`Portatil_modelo` ASC, `Portatil_marca` ASC),
  CONSTRAINT `usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`Usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `empleado`
    FOREIGN KEY (`empleado_seguridad_social`)
    REFERENCES `mydb`.`Empleado` (`seguridad_social`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prestamo_Libro1`
    FOREIGN KEY (`Libro_ISBN`)
    REFERENCES `mydb`.`Libro` (`ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prestamo_Revista1`
    FOREIGN KEY (`Revista_titulo`)
    REFERENCES `mydb`.`Revista` (`titulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prestamo_Portatil1`
    FOREIGN KEY (`Portatil_modelo` , `Portatil_marca`)
    REFERENCES `mydb`.`Portatil` (`modelo` , `marca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sala` (
  `id` INT NOT NULL,
  `capacidad` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reservacion_de_sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reservacion_de_sala` (
  `sala_id` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `hora_inicio` TIME NOT NULL,
  `hora_fin` TIME NOT NULL,
  `empleado_seguridad_social` VARCHAR(20) NOT NULL,
  `usuario_id` INT NOT NULL,
  INDEX `fk_reading_room_reservation_library_member1_idx` (`empleado_seguridad_social` ASC),
  INDEX `fk_reading_room_reservation_student1_idx` (`usuario_id` ASC),
  PRIMARY KEY (`sala_id`, `hora_inicio`, `empleado_seguridad_social`, `usuario_id`, `fecha`),
  CONSTRAINT `empleado`
    FOREIGN KEY (`empleado_seguridad_social`)
    REFERENCES `mydb`.`Empleado` (`seguridad_social`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `sala`
    FOREIGN KEY (`sala_id`)
    REFERENCES `mydb`.`Sala` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Delito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Delito` (
  `fecha` DATE NOT NULL,
  `usuario_id` INT NOT NULL,
  `empleado_seguridad_social` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`fecha`, `usuario_id`),
  INDEX `fk_deadline_infraction_student1_idx` (`usuario_id` ASC),
  INDEX `fk_deadline_infraction_library_member1_idx` (`empleado_seguridad_social` ASC),
  CONSTRAINT `usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `empleado`
    FOREIGN KEY (`empleado_seguridad_social`)
    REFERENCES `mydb`.`Empleado` (`seguridad_social`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Charla`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Charla` (
  `titulo` VARCHAR(45) NOT NULL,
  `usuario_id` INT NULL,
  `categoria_id` INT NULL,
  PRIMARY KEY (`titulo`),
  INDEX `usuario_idx` (`usuario_id` ASC),
  INDEX `categoria_idx` (`categoria_id` ASC),
  CONSTRAINT `usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `categoria`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `mydb`.`Categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reaccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reaccion` (
  `id` INT NOT NULL,
  `delito_fecha` DATE NOT NULL,
  `usuario_id` INT NOT NULL,
  `mensaje` VARCHAR(45) NULL,
  `fecha` DATE NULL,
  PRIMARY KEY (`id`, `delito_fecha`, `usuario_id`),
  INDEX `delito_idx` (`delito_fecha` ASC, `usuario_id` ASC),
  CONSTRAINT `delito`
    FOREIGN KEY (`delito_fecha` , `usuario_id`)
    REFERENCES `mydb`.`Delito` (`fecha` , `usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Prestamo_portatil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Prestamo_portatil` (
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `usuario_id` INT NOT NULL,
  `empleado_seguridad_social` VARCHAR(20) NOT NULL,
  `portatil_id` INT NOT NULL,
  INDEX `fk_book_borrow_service_student1_idx` (`usuario_id` ASC),
  INDEX `fk_book_reservation_library_member1_idx` (`empleado_seguridad_social` ASC),
  PRIMARY KEY (`empleado_seguridad_social`, `usuario_id`, `fecha_inicio`, `portatil_id`),
  INDEX `portatil_idx` (`portatil_id` ASC),
  CONSTRAINT `usuario0`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `empleado0`
    FOREIGN KEY (`empleado_seguridad_social`)
    REFERENCES `mydb`.`Empleado` (`seguridad_social`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `portatil`
    FOREIGN KEY (`portatil_id`)
    REFERENCES `mydb`.`Portatil` (`recurso_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Coleccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Coleccion` (
  `id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  `coleccion` LONGBLOB NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`),
  INDEX `usuario_idx` (`usuario_id` ASC),
  CONSTRAINT `usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
